global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "logstash-exporter"
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["exporter:9198"]
