logstash:
  enabled: true
  config: |
    input {
        generator {
            type => "dummy"
            count => -1
            message => '{"message": "dummy log"}'
        }
    }

    filter {
        json {
            source => "message"
        }
    }

    output {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
        }
    }

prometheus:
  enabled: true
  service:
    type: ClusterIP
  config: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "logstash-exporter"
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: "/metrics"
        scheme: "http"
        static_configs:
          - targets: ["exporter:9198"]

elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  esJavaOpts: "-Xms512m -Xmx512m"

logstash-exporter:
  enabled: true
